### ISSUE TITLE
Can't use element init

### ISSUE THREAD

**Issue by femdev** [flood-io/element#39] opened 2019-03-26 18:02 UTC
**Describe the bug**
On Mac OS High Sierra - get error when trying to use 'element init'

**To Reproduce**
1. On Mac OS High Sierra, run 'brew install flood-io/taps/element'
2. Run element init after install

Result:
➜  Prompt element init
> 'UPDATE AVAILABLE' The latest   version of Element CLI is 1.0.4
> Get it by running yarn global upgrade @flood/element-cli@latest
initting into /Users/elise/Repos/PluginTests
? The title of this test. (PluginTests) > Error! An unexpected empty rejection occurred
 rejection: null
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md

**Expected behavior**
Expected no error! It claims I already have 1.0.4 if trying to update as well. 

**Screenshots**

**Desktop (please complete the following information):**
Mac OS High Sierra

**Additional context**

**Comment by ivanvanderbyl** [comment] 2019-04-30 02:13
@femdev did you try updating Element?

**Comment by lachie** [comment] 2019-06-18 04:23
Could be related to #36 
@femdev we'd need more info on where you're running this from.

**Comment by mohan-ally** [comment] 2019-11-15 19:25
I am also facing the same issue https://share.getcloudapp.com/NQueX4bK
https://share.getcloudapp.com/X6u265zd

**Comment by dorrogeray** [comment] 2020-02-08 21:15
I can confirm this issue:

*Desktop:*

OS: Ubuntu 18.04
Node.js version: 12.13
Version 1.0.10-beta.45

**Comment by ivanvanderbyl** [comment] 2020-03-18 01:21
@dorrogeray sorry about that, it should be fixed in the latest beta `1.0.10-beta.52`

**Comment by skurra** [comment] 2020-03-21 10:12
How do we download this beta version?

**Comment by ivanvanderbyl** [comment] 2020-03-21 22:36
With yarn:
```
yarn global upgrade @flood/element-cli@beta
```

or with NPM:
```
npm -g install @flood/element-cli@beta
```

**Comment by linklink36** [comment] 2020-04-01 15:51
I tried this way but cannot resolve, still getting 
> Error! An unexpected empty rejection occurred
 rejection: null
It's weird that yesterday I can run smoothly, however today I am getting error while uisng same script :(. Any idea?

**Comment by jkroepke** [comment] 2020-04-01 16:55
I get this on element run, too.

element Version: 1.0.10-beta.63

**Comment by ivanvanderbyl** [comment] 2020-04-01 18:21
@jkroepke @linklink36 Is this happening when running a test (`element run`) or with another command?

**Comment by linklink36** [comment] 2020-04-01 18:23
it's when running 'element run script.ts'

**Comment by ivanvanderbyl** [comment] 2020-04-01 18:25
Thanks, I'll take a look and try to replicate.

**Comment by jkroepke** [comment] 2020-04-01 19:31
Yep element run.

The test file is maybe unrelated since I get this error even if the whole file is comment out.

**Comment by HieuLeKMS** [comment] 2020-06-03 07:14
Using brew will now install the latest stable version of Element (1.2.3), this issue should've already been fixed

**Closed** 2020-06-03 07:14 UTC
Labels: bug

**Comment by torfmaster** [comment] 2020-10-02 21:11
This issue re-occurs in element 1.3.7 with node v14. Is this regression?

**Comment by HieuLeKMS** [comment] 2020-10-03 14:50
@torfmaster I can't seem to reproduce the issue. Could you show me the error that you're getting?

**Comment by torfmaster** [comment] 2020-10-04 10:40
@HieuLeKMS:

Here's some output:
```
> npx element run XXXX --no-headless

> INFO UPDATE AVAILABLE The latest stable version of element-cli is 1.3.8
> INFO Get it by running yarn global upgrade element-cli@latest
+0s info: workRootPath: XXXXX
+0s info: testDataPath: XXXXX
Running the test with:
- Element v1.3.8
- Node v14.5.0

● Script Compiler █████████████████████████ compiling (0%)  
 

> Error! An unexpected empty rejection occurred
 rejection: null
```
What puzzles me is that the output says that element v1.3.8 is used although my package.json says that 1.3.7 should be used.

**Comment by HieuLeKMS** [comment] 2020-10-05 02:27
@torfmaster 
I'm guessing that element's version in your package.json is `^1.3.7`, because of the `^`, the latest compatible version will be installed, which is 1.3.8.
And about the error you're getting, updating your global installed element to 1.3.8 should fix it. Update it by running `yarn global upgrade element-cli@latest`. You might also need to uninstall your current global element first.

**Comment by torfmaster** [comment] 2020-10-06 06:45
> I'm guessing that element's version in your package.json is ^1.3.7, because of the ^, 

I'm actually using "1.3.7" without the ^ so 1.3.8 shouldn't be installed. However, upgrading to 1.3.8 fixes the issue. Thanks for your support.

**Comment by richard015ar** [comment] 2020-11-05 18:59
I just ran my script with element cli, and stopped it immediately and from that moment I started to get this error.
I restarted my computer and everything worked well. I tried to see if there is a process in background maybe couldn't closed. But nothing strange on my processes list.
Restarting my computer solved this problem in my case.
