### ISSUE TITLE
running element init on mac when there is a space in path fails

### ISSUE THREAD

**Issue by cpvalcourt** [flood-io/element#36] opened 2019-01-20 19:09 UTC
**Describe the bug**
After installaing with "npm install -g @flood/element-cli" and running "element init" results in permission error

**To Reproduce**
1. run "npm install -g @flood/element-cli"
2. run "element init <anything>
3. See error:
Chriss-MBP:flood cvalcourt$ element init riv --verbose
> Error! An unexpected error occurred!
  Error: EACCES: permission denied, mkdir '/Users/christopher'
    at Object.fs.mkdirSync (fs.js:885:18)
    at make (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/make-dir/index.js:61:12)
    at Function.module.exports.sync (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/make-dir/index.js:84:9)
    at TestEnv.destinationRoot (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/yeoman-generator/lib/index.js:644:17)
    at TestEnv.initializing (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/dist/src/generator/test-env/index.js:22:14)
    at Object.<anonymous> (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/yeoman-generator/lib/index.js:425:13) Error: EACCES: permission denied, mkdir '/Users/christopher'
    at Object.fs.mkdirSync (fs.js:885:18)
    at make (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/make-dir/index.js:61:12)
    at Function.module.exports.sync (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/make-dir/index.js:84:9)
    at TestEnv.destinationRoot (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/yeoman-generator/lib/index.js:644:17)
    at TestEnv.initializing (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/dist/src/generator/test-env/index.js:22:14)
    at Object.<anonymous> (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/christopher valcourt/.nvm/versions/node/v8.12.0/lib/node_modules/@flood/element-cli/node_modules/yeoman-generator/lib/index.js:425:13)
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md

**Expected behavior**
A project is initialized

**Screenshots**
n/a see description above

**Desktop (please complete the following information):**
 - OS: macOS 10.14 (18A391)
 - Node.js version: v8.12.0
 - Version 1.0.4

**Additional context**
n/a

**Comment by slavkoilic** [comment] 2019-03-07 14:10
Just to add that this behavior is the same on Windows as well.
Error log is a bit different, but the root cause is the same: 
- Tried to init project on a path containing spaces - it fails.
- Tried to init project on a path containing no spaces - it succeeds.

**Comment by lachie** [comment] 2019-06-18 04:11
Hi, I've fixed this in the latest beta (1.0.5-beta.10), which should be released in the next couple of days.

**Comment by phileba** [comment] 2020-04-21 07:37
@lachie has fixed so this issue should be closed

**Closed by phileba** 2020-04-21 07:37 UTC
Labels: bug
